package com.example.eg09batch.base.application.repository.mbg;

import com.example.eg09batch.base.domain.model.mbg.BatchJobInstance;
import com.example.eg09batch.base.domain.model.mbg.BatchJobInstanceExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface BatchJobInstanceRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_instance
     *
     * @mbg.generated
     */
    long countByExample(BatchJobInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_instance
     *
     * @mbg.generated
     */
    List<BatchJobInstance> selectByExampleWithRowbounds(BatchJobInstanceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_instance
     *
     * @mbg.generated
     */
    List<BatchJobInstance> selectByExample(BatchJobInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_instance
     *
     * @mbg.generated
     */
    BatchJobInstance selectByPrimaryKey(Long jobInstanceId);
}