package com.example.eg09batch.base.application.repository.mbg;

import com.example.eg09batch.base.domain.model.mbg.BatchJobExecutionParams;
import com.example.eg09batch.base.domain.model.mbg.BatchJobExecutionParamsExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface BatchJobExecutionParamsRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_execution_params
     *
     * @mbg.generated
     */
    long countByExample(BatchJobExecutionParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_execution_params
     *
     * @mbg.generated
     */
    List<BatchJobExecutionParams> selectByExampleWithRowbounds(BatchJobExecutionParamsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_execution_params
     *
     * @mbg.generated
     */
    List<BatchJobExecutionParams> selectByExample(BatchJobExecutionParamsExample example);
}