package com.example.eg09batch.base.application.repository.mbg;

import com.example.eg09batch.base.domain.model.mbg.BatchStepExecution;
import com.example.eg09batch.base.domain.model.mbg.BatchStepExecutionExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface BatchStepExecutionRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_step_execution
     *
     * @mbg.generated
     */
    long countByExample(BatchStepExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_step_execution
     *
     * @mbg.generated
     */
    List<BatchStepExecution> selectByExampleWithRowbounds(BatchStepExecutionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_step_execution
     *
     * @mbg.generated
     */
    List<BatchStepExecution> selectByExample(BatchStepExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_step_execution
     *
     * @mbg.generated
     */
    BatchStepExecution selectByPrimaryKey(Long stepExecutionId);
}