package com.example.eg09batch.base.application.repository.mbg;

import com.example.eg09batch.base.domain.model.mbg.BatchJobExecutionContext;
import com.example.eg09batch.base.domain.model.mbg.BatchJobExecutionContextExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface BatchJobExecutionContextRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_execution_context
     *
     * @mbg.generated
     */
    long countByExample(BatchJobExecutionContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_execution_context
     *
     * @mbg.generated
     */
    List<BatchJobExecutionContext> selectByExampleWithRowbounds(BatchJobExecutionContextExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_execution_context
     *
     * @mbg.generated
     */
    List<BatchJobExecutionContext> selectByExample(BatchJobExecutionContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_job_execution_context
     *
     * @mbg.generated
     */
    BatchJobExecutionContext selectByPrimaryKey(Long jobExecutionId);
}