package com.example.eg09batch.base.application.repository.mbg;

import com.example.eg09batch.base.domain.model.mbg.BatchStepExecutionContext;
import com.example.eg09batch.base.domain.model.mbg.BatchStepExecutionContextExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface BatchStepExecutionContextRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_step_execution_context
     *
     * @mbg.generated
     */
    long countByExample(BatchStepExecutionContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_step_execution_context
     *
     * @mbg.generated
     */
    List<BatchStepExecutionContext> selectByExampleWithRowbounds(BatchStepExecutionContextExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_step_execution_context
     *
     * @mbg.generated
     */
    List<BatchStepExecutionContext> selectByExample(BatchStepExecutionContextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_step_execution_context
     *
     * @mbg.generated
     */
    BatchStepExecutionContext selectByPrimaryKey(Long stepExecutionId);
}