package com.example.eg09batch.dataSync.application.repository;

import com.example.eg09batch.dataSync.domain.model.MUser;
import com.example.eg09batch.dataSync.domain.model.MUserExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface MUserRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    List<MUser> selectByExampleWithRowbounds(MUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated
     */
    List<MUser> selectByExample(MUserExample example);
}