package com.example.eg09batch.base.domain.model.mbg;

import java.io.Serializable;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table batch_job_instance
 */
@Data
public class BatchJobInstance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_instance.job_instance_id
     *
     * @mbg.generated
     */
    private Long jobInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_instance.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_instance.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_instance.job_key
     *
     * @mbg.generated
     */
    private String jobKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch_job_instance
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}