package com.example.eg09batch.base.domain.model.mbg;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table batch_step_execution
 */
@Data
public class BatchStepExecution implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.step_execution_id
     *
     * @mbg.generated
     */
    private Long stepExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.step_name
     *
     * @mbg.generated
     */
    private String stepName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.job_execution_id
     *
     * @mbg.generated
     */
    private Long jobExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.start_time
     *
     * @mbg.generated
     */
    private LocalDateTime startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.commit_count
     *
     * @mbg.generated
     */
    private Long commitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.read_count
     *
     * @mbg.generated
     */
    private Long readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.filter_count
     *
     * @mbg.generated
     */
    private Long filterCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.write_count
     *
     * @mbg.generated
     */
    private Long writeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.read_skip_count
     *
     * @mbg.generated
     */
    private Long readSkipCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.write_skip_count
     *
     * @mbg.generated
     */
    private Long writeSkipCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.process_skip_count
     *
     * @mbg.generated
     */
    private Long processSkipCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.rollback_count
     *
     * @mbg.generated
     */
    private Long rollbackCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.exit_code
     *
     * @mbg.generated
     */
    private String exitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.exit_message
     *
     * @mbg.generated
     */
    private String exitMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_step_execution.last_updated
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch_step_execution
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}