package com.example.eg09batch.base.domain.model.mbg;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table batch_job_execution
 */
@Data
public class BatchJobExecution implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.job_execution_id
     *
     * @mbg.generated
     */
    private Long jobExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.job_instance_id
     *
     * @mbg.generated
     */
    private Long jobInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.start_time
     *
     * @mbg.generated
     */
    private LocalDateTime startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.exit_code
     *
     * @mbg.generated
     */
    private String exitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.exit_message
     *
     * @mbg.generated
     */
    private String exitMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.last_updated
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution.job_configuration_location
     *
     * @mbg.generated
     */
    private String jobConfigurationLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch_job_execution
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}