package com.example.eg09batch.base.domain.model.mbg;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table batch_job_execution_params
 */
@Data
public class BatchJobExecutionParams implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution_params.job_execution_id
     *
     * @mbg.generated
     */
    private Long jobExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution_params.type_cd
     *
     * @mbg.generated
     */
    private String typeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution_params.key_name
     *
     * @mbg.generated
     */
    private String keyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution_params.string_val
     *
     * @mbg.generated
     */
    private String stringVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution_params.date_val
     *
     * @mbg.generated
     */
    private LocalDateTime dateVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution_params.long_val
     *
     * @mbg.generated
     */
    private Long longVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution_params.double_val
     *
     * @mbg.generated
     */
    private Double doubleVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_job_execution_params.identifying
     *
     * @mbg.generated
     */
    private String identifying;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch_job_execution_params
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}